apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ab
  name: ab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ab
  template:
    metadata:
      labels:
        app: ab
    spec:
      containers:
      - image: devth/alpine-bench
        name: ab
        command: ["/bin/sh", "-c", "while true; do ab -n$(requests) -c$(concurrency) -s$(timeout) $(url); done"]
        envFrom:
        - configMapRef:
            name: ab-config
